// Score Actions
export const UPDATE_NATURE_SCORE = "UPDATE_NATURE_SCORE";
export const UPDATE_ANIMALS_SCORE = "UPDATE_ANIMALS_SCORE";
export const UPDATE_FOOD_SCORE = "UPDATE_FOOD_SCORE";

// Game Status Actions
export const UPDATE_GAME_STATE = "UPDATE_GAME_STATE";
export const UPDATE_IMAGES = "UPDATE_IMAGES";
export const RESET_GAME_STATE = "RESET_GAME_STATE";